### ISSUE TITLE
Plot residuals vs. visit metadata

### ISSUE THREAD

**Issue by davidwhogg** [adrn/TwoFace#12]
[Edited heavily by @adrn to generalize]

Each visit corresponds to a given plate, fiber number, LN2 fill level, etc. For the samplings we have, take the best-fit orbit sample, compute the residuals at each visit, and plot these (signed) residuals as a function of:
* [x] fiber ID
* [x] plate ID
* [ ] LN2 fill level
* [ ] persistence flag (note: we exclude PERSIST_HIGH stars in the current run, so can't do right now)
* others?

Things to check:
* Are there trends with the above?
* Do fibers near the edge of the plate look systematically worse?

**Comment by adrn** [comment]
One more way of looking at this. Here is a histogram of the same residuals as above, with a gaussian of width 150 m/s plotted over (blue):

![image](https://user-images.githubusercontent.com/583379/36355393-87987d86-14b0-11e8-8e55-b74c0090c398.png)

**Comment by davidwhogg** [comment]
Can you overplot medians ?

**Comment by davidwhogg** [comment]
And maybe other quantiles?

**Comment by adrn** [comment]
Quantiles for all visits of a given plate/fiber/mjd?

**Comment by davidwhogg** [comment]
running quantiles with some window in MJD, PLATEID, and FIBERID. On the three-panel plot.

**Comment by adrn** [comment]
![image](https://user-images.githubusercontent.com/583379/36742932-fb523336-1bb6-11e8-9e5b-3bb90277fff6.png)

**Comment by adrn** [comment]
Also interesting, all visit residuals from the best-fitting orbit sample normalized by sqrt(v_err**2 + jitter**2)
![image](https://user-images.githubusercontent.com/583379/36742997-2447109a-1bb7-11e8-8090-6f80282292c4.png)
