### ISSUE TITLE
Audit usage of the word 'jitter,' change to 'excess variance'

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#14]
Jitter means something specific in the stellar community, so we should be careful about overlapping terminology.

**Comment by davidwhogg** [comment]
Just be careful with the word variance which is measured in speed-squared units. I think we can have it all.

**Comment by davidwhogg** [comment]
Just be careful with the word variance which is measured in speed-squared units. I think we can have it all.

**Comment by adrn** [comment]
Done
