### ISSUE TITLE
Rescope results section for paper 1

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#15]
We discussed comparing RGB to RC companions, and later (this morning) RC vs. subgiant. I now think that for the catalog paper, it might be sufficient to just highlight interesting RC companions: things that would have been within the envelope of the star at the TRGB. I now think that the RC to subgiant/RGB comparison warrants its own paper.

Thoughts @davidwhogg ?

**Comment by davidwhogg** [comment]
Agree! Let’s keep reducing scope. This project is huge!

**Comment by adrn** [comment]
Done
