### ISSUE TITLE
MCMC following TheJoker sampling

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#16]
Here are 3 stars that got flagged "needs mcmc" by _The Joker_. I followed up with MCMC (`emcee`) using 2048 walkers (!) - see plots below:

# 2M17053511+3516091
![test-mcmc-2m17053511 3516091](https://user-images.githubusercontent.com/583379/36355633-52760804-14b4-11e8-9374-26db07d6fb5a.png)

# 2M17090565+3206318
![test-mcmc-2m17090565 3206318](https://user-images.githubusercontent.com/583379/36355635-53c61a00-14b4-11e8-9530-ffdec65686fd.png)

# 2M17091769+3127589
![test-mcmc-2m17091769 3127589](https://user-images.githubusercontent.com/583379/36355637-56a2269c-14b4-11e8-835c-b7bb57402a3a.png)

**Comment by adrn** [comment]
Here's the data for the 3 stars (in the same order), with 256 orbits plotted taken from the final positions of the walkers:

# 2M17053511+3516091
![2m17053511 3516091-samples](https://user-images.githubusercontent.com/583379/36355668-c79c9134-14b4-11e8-86be-dcad99fcfe54.png)

# 2M17090565+3206318
![2m17090565 3206318-samples](https://user-images.githubusercontent.com/583379/36355670-cb19ccdc-14b4-11e8-8744-ab1a6e061d9b.png)

# 2M17091769+3127589
![2m17091769 3127589-samples](https://user-images.githubusercontent.com/583379/36355671-d24bdee6-14b4-11e8-822c-4ba7c2dfb13e.png)

**Comment by adrn** [comment]
My impression from this is that the speed of convergence depends on the phase coverage: for the top 2 stars, the curvature at max/min isn't resolved. I'll run on all "needs mcmc" stars with 1024 walkers for 16384 steps and we can check it out (because, you know, that's only ~300 GB of samples !!).

**Comment by davidwhogg** [comment]
Smells like reparameterization... for paper N

**Comment by adrn** [comment]
Any objections to reporting max. over parameters of the Gelman-Rubin statistic as a way to gauge convergence? I went up to 65536 steps and autocorrelation time estimates still weren't converging...

**Comment by davidwhogg** [comment]
Fine with me.
