### ISSUE TITLE
Period samples vs. logg

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#17]
Plotted below for stars with >= 12 epochs. Colored lines show the orbital period of a test particle at the surface of a star with different masses (colors) with a given logg.

I don't know what to make of this!

![image](https://user-images.githubusercontent.com/583379/36356110-07679a10-14bb-11e8-9aec-21ee27449347.png)

**Comment by adrn** [comment]
The lines in the plot above should move to shorter periods (to the left) for realistic (i.e. massive) companions! The test particle assumption is bad

**Comment by adrn** [comment]
Here's the same for only stars with allegedly unimodal posterior samplings -- the dearth of points between 10–100 days around logg=2 catches my eye! 

![image](https://user-images.githubusercontent.com/583379/36356156-b2daa16c-14bb-11e8-9a4e-b106f3595b80.png)

**Comment by davidwhogg** [comment]
Are we seeing coherent asteroseismic modes??

**Comment by davidwhogg** [comment]
Let's put in the paper examples of stars that are impossible wrt companions; ie, well-determined companion at period too short.

**Comment by adrn** [comment]
> Dude can you re-make this plot with two changes:
> 
> (1) coloring each sample point by the value of v sin i (and adding a colorbar), and
> 
> (2) giving each point an alpha which is 1/K where K is the number of samples that survived the sampling. Or maybe sqrt of that. Or something sensible.
> 
> Rix points out that vsini amplitudes should rise as you approach the lines from the right and drop as soon as you cross them!
>

**Comment by davidwhogg** [comment]
We should split asteroseismology out to a separate repository, with a new Joker, where the nonlinear parameters are numax, deltanu, and some nu_0...

**Comment by adrn** [comment]
A few more plots:

![image](https://user-images.githubusercontent.com/583379/36685944-de9e031a-1af2-11e8-9451-13c94fdeedf5.png)

![image](https://user-images.githubusercontent.com/583379/36685947-e1c02f14-1af2-11e8-88e2-c126a3b9be37.png)

![image](https://user-images.githubusercontent.com/583379/36685949-e4ec0b2c-1af2-11e8-9717-fce2ab6a122e.png)

**Comment by adrn** [comment]
Note from Renbin: Can we see optical variability in APASS photometry?

**Comment by adrn** [comment]
Turned this into several other issues
