### ISSUE TITLE
How should we threshold in K?

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#21]
Here's distributions of percentiles in lnK for the APOGEE posterior samples

![image](https://user-images.githubusercontent.com/583379/36610623-e05d090e-189e-11e8-82e5-0a1310788da7.png)

**Comment by adrn** [comment]
Another possible table: objects with only a few qualitatively different orbits

**Comment by adrn** [comment]
Here's the same for a control sample!

I made the control sample as follows:
* Randomly pick 16,384 stars from our parent sample
* Sample an excess variance parameter value from our prior
* Re-sample the visit velocities assuming no RV variations with mean = mean(data), variance = (visit uncertainty^2) + (excess variance)
* "Forget" the excess variance parameter value 

Then I ran TheJoker on all of the simulated (no companion) control sample data and made the same plot as above.

![image](https://user-images.githubusercontent.com/583379/36817965-152c6d4e-1cb1-11e8-9b1c-5707bbbcf5d8.png)

**Comment by davidwhogg** [comment]
I'm good with that!! But we could go lower if we wanted to...

**Comment by adrn** [comment]
If we go to 5% FPR / lnK = -0.88, that's 7697 companions. I don't have strong feelings on which to use!

**Comment by adrn** [comment]
I'll use the 1% FPR cut for now, but we should discuss. It's easy to change...
