### ISSUE TITLE
Time-domain photometry for our sample?

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#27]
Search for eclipses!

**Comment by adrn** [comment]
The problem: our stars are *bright* -- PTF and PS1 both saturate at R~14. What other surveys are there?

**Comment by adrn** [comment]
@davidwhogg dude! see above

**Comment by davidwhogg** [comment]
O M G . This is great! I love the sinusoidal one too; that's HUGE. Is it a sinusoidal pulsator?

**Comment by adrn** [comment]
Out of scope for paper 1!
