### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#3]
Here's a poor-man's schema for what I'm thinking:

![image](https://cloud.githubusercontent.com/assets/583379/21598659/690f0838-d12e-11e6-9768-ef3ba86bc04f.png)

**Comment by adrn** [comment]
Ah, AllStar to AllVisit is only many-to-many on the column `APOGEE_ID` -- apparently `TARGET_ID` is unique to both...so the join table is a little unnecessary. That's because the same `APOGEE_ID` can be a part of two target / cadence programs (e.g., `APOGEE_LONG` and `APOGEE_SHORT`). From looking at the SDSS documentation, it's not really clear to me whether I can take all RV's from a `TARGET_ID` and lump them together (i.e. is it safe to combine `APOGEE_LONG` and `APOGEE_SHORT` exposures?) or whether I should analyze these separately? Maybe @davidwhogg has an idea of who to ask?

**Comment by davidwhogg** [comment]
Formulate this as an email to me and mkness
