### ISSUE TITLE
Improve visit quality cuts

### ISSUE THREAD

**Issue by adrn** [adrn/TwoFace#9]

**Comment by davidwhogg** [comment]
Talk to me: Are there issues?

**Comment by mkness** [comment]
I don't think you should do an snr cut, but I have found removing badstar flagged stars and fast rotators to be a thorough cut to get a clean sample.

**Comment by davidwhogg** [comment]
We could check whether our (squared) velocity residuals grow as SNR decreases in the expected way. But I think it is out of scope, given the @mkness comment

**Comment by adrn** [comment]
I still think we need to do some quality cuts at the visit level -- as far as I can tell, filtering out `STAR_BAD` (i.e. at the star level) won't catch bad visits, and we need to weed those out as well. That said, I just looked at the numbers from my initial cuts and I think they were too strict: in the run I have on hand, we only have ~92,000 stars with >=3 visits because 1/2 of all visits (~500,000) were flagged as bad!

Here is my new proposal for cuts **at the visit level**:
* VHELIO, VRELERR not NaN
* VRELERR < 100 (km/s) - there are ~1000 stars with VRELERR ~ 1000000000 (WTF)
* exclude: PERSIST_HIGH, PERSIST_JUMP_POS, PERSIST_JUMP_NEG
* exclude: VERY_BRIGHT_NEIGHBOR, LOW_SNR

At the star level:
* exclude STAR_BAD

This removes 283,505 of 1,000,000 visits.

**Comment by davidwhogg** [comment]
Holy crap crazy.

**Comment by adrn** [comment]
The APOGEE RV var peeps not react negatively towards these cuts - will roll with them for now!
